FROM python:3-alpine AS base

RUN apk add --update --no-cache gcc g++ musl-dev libffi-dev
RUN pip3 install --user --no-cache acmeasync docker jinja2 pyyaml pydantic

FROM python:3-alpine
# END COMMON

RUN apk add --update --no-cache openssl

WORKDIR /app
COPY common.py config.py controller.py nginx.conf.jinja ./
COPY --from=base /root/.local /root/.local

CMD ["python", "controller.py"]
